/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 iso_room.glb 
Author: Graf_Lev (https://sketchfab.com/Graf_Lev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/isometric-rec-room-d30c226a81b141c58bbb704fefe8530e
Title: Isometric Rec Room
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { convert } from 'three/tsl'
import { convertToBasicMaterials } from '../utility/convertToBasic'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/iso_room.glb')
 
 
const newMaterials = convertToBasicMaterials(materials);
  
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-324.991, 93.201, 161.938]} rotation={[-1.567, -0.141, 0.029]} scale={[12.608, 16.653, 12.608]}>
          <mesh geometry={nodes.Plane015_White_0.geometry} material={newMaterials.White} />
          <mesh geometry={nodes.Circle027_Black_0.geometry} material={newMaterials.Black} position={[-0.212, -0.61, 0.81]} rotation={[0, 0.002, Math.PI / 2]} scale={[0.387, 0.512, 0.512]} />
          <mesh geometry={nodes.Circle028_Black_0.geometry} material={newMaterials.Black} position={[0.606, 0.449, 0.701]} rotation={[0, 0.184, Math.PI / 2]} scale={[0.372, 0.492, 0.492]} />
          <mesh geometry={nodes.Circle029_Black_0.geometry} material={newMaterials.Black} position={[0.63, -0.434, 0.679]} rotation={[0, 0.224, Math.PI / 2]} scale={[0.217, 0.287, 0.287]} />
          <mesh geometry={nodes.Plane017_Black_0.geometry} material={newMaterials.Black} position={[0.053, 0, 0]} />
          <mesh geometry={nodes.Circle030_Black_0.geometry} material={newMaterials.Black} position={[-0.63, 0.001, 0.809]} rotation={[0, -0.091, Math.PI / 2]} scale={[0.197, 0.261, 0.261]} />
          <mesh geometry={nodes.Circle031_Black_0.geometry} material={newMaterials.Black} position={[-0.31, 0.651, 0.813]} rotation={[-0.007, -0.007, 1.578]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle032_Black_0.geometry} material={newMaterials.Black} position={[-0.086, 0.487, 0.817]} rotation={[-0.015, 0.012, 1.616]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle033_Black_0.geometry} material={newMaterials.Black} position={[0.145, 0.641, 0.794]} rotation={[-0.016, 0.117, 1.58]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle034_Black_0.geometry} material={newMaterials.Black} position={[-0.066, 0.807, 0.794]} rotation={[-0.102, 0.026, 1.581]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle035_Black_0.geometry} material={newMaterials.Black} position={[-0.025, -0.181, 0.834]} rotation={[0, 0.062, Math.PI / 2]} scale={[0.07, 0.092, 0.092]} />
          <mesh geometry={nodes.Plane016_Black_0.geometry} material={newMaterials.Black} position={[0.218, 0.001, 0.817]} rotation={[0, 0.044, Math.PI / 2]} scale={[0.12, 0.065, 0.065]} />
        </group>
        <group position={[-339.672, 93.201, 73.416]} rotation={[-1.511, -0.127, 0.438]} scale={[12.608, 16.653, 12.608]}>
          <mesh geometry={nodes.Plane019_White_0.geometry} material={newMaterials.White} />
          <mesh geometry={nodes.Circle042_Black_0.geometry} material={newMaterials.Black} position={[-0.212, -0.61, 0.81]} rotation={[0, 0.002, Math.PI / 2]} scale={[0.387, 0.512, 0.512]} />
          <mesh geometry={nodes.Circle043_Black_0.geometry} material={newMaterials.Black} position={[0.606, 0.449, 0.701]} rotation={[0, 0.184, Math.PI / 2]} scale={[0.372, 0.492, 0.492]} />
          <mesh geometry={nodes.Circle044_Black_0.geometry} material={newMaterials.Black} position={[0.63, -0.434, 0.679]} rotation={[0, 0.224, Math.PI / 2]} scale={[0.217, 0.287, 0.287]} />
          <mesh geometry={nodes.Plane020_Black_0.geometry} material={newMaterials.Black} position={[0.053, 0, 0]} />
          <mesh geometry={nodes.Circle036_Black_0.geometry} material={newMaterials.Black} position={[-0.63, 0.001, 0.809]} rotation={[0, -0.091, Math.PI / 2]} scale={[0.197, 0.261, 0.261]} />
          <mesh geometry={nodes.Circle037_Black_0.geometry} material={newMaterials.Black} position={[-0.31, 0.651, 0.813]} rotation={[-0.007, -0.007, 1.578]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle038_Black_0.geometry} material={newMaterials.Black} position={[-0.086, 0.487, 0.817]} rotation={[-0.015, 0.012, 1.616]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle039_Black_0.geometry} material={newMaterials.Black} position={[0.145, 0.641, 0.794]} rotation={[-0.016, 0.117, 1.58]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle040_Black_0.geometry} material={newMaterials.Black} position={[-0.066, 0.807, 0.794]} rotation={[-0.102, 0.026, 1.581]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle041_Black_0.geometry} material={newMaterials.Black} position={[-0.025, -0.181, 0.834]} rotation={[0, 0.062, Math.PI / 2]} scale={[0.07, 0.092, 0.092]} />
          <mesh geometry={nodes.Plane018_Black_0.geometry} material={newMaterials.Black} position={[0.218, 0.001, 0.817]} rotation={[0, 0.044, Math.PI / 2]} scale={[0.12, 0.065, 0.065]} />
        </group>
        <group position={[-31.776, 107.516, 35.042]} rotation={[-1.481, -0.108, 0.695]} scale={[12.608, 16.653, 12.608]}>
          <mesh geometry={nodes.Plane022_White_0.geometry} material={newMaterials.White} />
          <mesh geometry={nodes.Circle051_Black_0.geometry} material={newMaterials.Black} position={[-0.212, -0.61, 0.81]} rotation={[0, 0.002, Math.PI / 2]} scale={[0.387, 0.512, 0.512]} />
          <mesh geometry={nodes.Circle052_Black_0.geometry} material={newMaterials.Black} position={[0.606, 0.449, 0.701]} rotation={[0, 0.184, Math.PI / 2]} scale={[0.372, 0.492, 0.492]} />
          <mesh geometry={nodes.Circle053_Black_0.geometry} material={newMaterials.Black} position={[0.63, -0.434, 0.679]} rotation={[0, 0.224, Math.PI / 2]} scale={[0.217, 0.287, 0.287]} />
          <mesh geometry={nodes.Plane023_Black_0.geometry} material={newMaterials.Black} position={[0.053, 0, 0]} />
          <mesh geometry={nodes.Circle045_Black_0.geometry} material={newMaterials.Black} position={[-0.63, 0.001, 0.809]} rotation={[0, -0.091, Math.PI / 2]} scale={[0.197, 0.261, 0.261]} />
          <mesh geometry={nodes.Circle046_Black_0.geometry} material={newMaterials.Black} position={[-0.31, 0.651, 0.813]} rotation={[-0.007, -0.007, 1.578]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle047_Black_0.geometry} material={newMaterials.Black} position={[-0.086, 0.487, 0.817]} rotation={[-0.015, 0.012, 1.616]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle048_Black_0.geometry} material={newMaterials.Black} position={[0.145, 0.641, 0.794]} rotation={[-0.016, 0.117, 1.58]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle049_Black_0.geometry} material={newMaterials.Black} position={[-0.066, 0.807, 0.794]} rotation={[-0.102, 0.026, 1.581]} scale={[0.096, 0.127, 0.127]} />
          <mesh geometry={nodes.Circle050_Black_0.geometry} material={newMaterials.Black} position={[-0.025, -0.181, 0.834]} rotation={[0, 0.062, Math.PI / 2]} scale={[0.07, 0.092, 0.092]} />
          <mesh geometry={nodes.Plane021_Black_0.geometry} material={newMaterials.Black} position={[0.218, 0.001, 0.817]} rotation={[0, 0.044, Math.PI / 2]} scale={[0.12, 0.065, 0.065]} />
        </group>
        <group position={[-325.5, 170.522, -201.24]} rotation={[0.2, -0.506, 0.066]} scale={[110.301, 102.794, 110.076]}>
          <mesh geometry={nodes.Plane027_Black_0.geometry} material={newMaterials.Black} />
          <mesh geometry={nodes.Cylinder001_Metall_0.geometry} material={newMaterials.Metall} position={[0.077, -0.251, 0.212]} rotation={[-2.356, 1.521, 0.612]} scale={0.013} />
          <mesh geometry={nodes.Plane025_Black_0.geometry} material={newMaterials.Black} position={[0.012, -0.275, 0.14]} rotation={[-0.032, 0.023, 0.029]} scale={[1.036, 1.111, 1.038]} />
          <mesh geometry={nodes.Plane026_Metall_0.geometry} material={newMaterials.Metall} position={[0.013, -0.314, 0.16]} rotation={[-0.001, 0.024, 0.028]} scale={1.056} />
          <mesh geometry={nodes.Plane028_Metall_0.geometry} material={newMaterials.Metall} position={[0.005, -0.019, 0.134]} rotation={[0.309, 0.025, -0.002]} scale={[1.5, 1.926, 1.95]} />
          <mesh geometry={nodes.Circle058_Floor001_0.geometry} material={newMaterials['Floor.001']} position={[0.025, -0.79, 0.017]} rotation={[-1.746, -0.031, 0.017]} scale={[0.039, 0.059, 0.059]} />
        </group>
        <group position={[137.807, 123.378, -348.534]} rotation={[-Math.PI / 2, 0, -0.272]} scale={110.838}>
          <mesh geometry={nodes.Plane030_Black_0.geometry} material={newMaterials.Black} />
          <mesh geometry={nodes.Plane030_Black005_0.geometry} material={newMaterials['Black.005']} />
        </group>
        <group position={[305.283, 67.374, 314.389]} rotation={[-Math.PI / 2, 0, -0.591]} scale={193.096}>
          <mesh geometry={nodes['Plant_Ficus_A_spring-summer-autumn|Plant_Ficus_A_spring-summer-autumn_L_Plant_Ficus_A_spring-summer-autumnblend|Dupli|_bq_Stem_Ficus_0'].geometry} material={newMaterials.bq_Stem_Ficus} />
          <mesh geometry={nodes['Plant_Ficus_A_spring-summer-autumn|Plant_Ficus_A_spring-summer-autumn_L_Plant_Ficus_A_spring-summer-autumnblend|Dupli|_bq_Leaf_Ficus_0'].geometry} material={newMaterials.bq_Leaf_Ficus} />
        </group>
        <group position={[-36.4, 108.34, -72.208]} rotation={[-Math.PI / 2, 0, -0.281]} scale={100}>
          <mesh geometry={nodes.Plane024_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Circle055_Metall_0.geometry} material={materials.Metall} position={[-0.223, 0.044, 0.018]} rotation={[-Math.PI, 0, 0]} scale={[-0.016, 0.016, 0.016]} />
          <mesh geometry={nodes.Circle056_Metall_0.geometry} material={materials.Metall} position={[-0.002, 0.024, 0.018]} rotation={[Math.PI, 0, 0]} scale={[-0.018, 0.018, 0.018]} />
          <mesh geometry={nodes.Circle057_Metall_0.geometry} material={materials.Metall} position={[0.002, 0.024, 0.018]} rotation={[Math.PI, 0, 0]} scale={[-0.018, 0.018, 0.018]} />
          <mesh geometry={nodes.Circle054_Metall_0.geometry} material={materials.Metall} position={[-0.111, 0, 0.001]} scale={0.063} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={400}>
          <mesh geometry={nodes.Plane_Floor_0.geometry} material={materials.Floor} />
          <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane_Wall_0.geometry} material={materials.Wall} />
        </group>
        <group position={[228.44, 36.077, -162.668]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Cube002_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Cube003_White_0.geometry} material={materials.White} position={[1.2, -0.35, 0.877]} scale={0.924} />
          <mesh geometry={nodes.Cube004_White_0.geometry} material={materials.White} position={[-0.538, 0.668, 0.506]} scale={[2.519, 0.338, 1.41]} />
          <mesh geometry={nodes.Cube005_Black_0.geometry} material={materials.Black} position={[1.037, -0.855, 1.39]} />
          <mesh geometry={nodes.Cube007_Black_0.geometry} material={materials.Black} position={[-0.538, 0.668, 0.506]} scale={[2.519, 0.338, 1.41]} />
          <mesh geometry={nodes.Circle001_Metall_0.geometry} material={materials.Metall} position={[-0.003, -0.188, 0.684]} scale={0.153} />
          <mesh geometry={nodes.Cube008_Black_0.geometry} material={materials.Black} position={[0.311, -0.191, 0.673]} scale={[2.519, 0.338, 1.41]} />
          <mesh geometry={nodes.Circle002_Metall_0.geometry} material={materials.Metall} position={[0.41, -0.188, 0.684]} scale={0.153} />
          <mesh geometry={nodes.Circle004_Metall_0.geometry} material={materials.Metall} position={[0.034, 1.896, 0.899]} scale={0.153} />
          <mesh geometry={nodes.Cube006_Black_0.geometry} material={materials.Black} position={[0.311, -3.541, 0.673]} scale={[2.519, 0.338, 1.41]} />
        </group>
        <group position={[-48.785, 53.544, 54.252]} rotation={[-Math.PI / 2, 0, 0]} scale={[75.013, 105.965, 123.719]}>
          <group position={[0.004, 1.241, -0.107]} scale={[2.259, 0.966, 0.966]}>
            <mesh geometry={nodes.Plane003_Metall_0.geometry} material={materials.Metall} />
            <mesh geometry={nodes.Plane003_Black001_0.geometry} material={materials['Black.001']} />
          </group>
          <mesh geometry={nodes.Plane004_Marble003_0.geometry} material={materials['Marble.003']} />
          <mesh geometry={nodes.Circle006__0.geometry} material={materials['Circle.006__0']} position={[0.006, 1.174, -0.112]} scale={[0.462, 0.317, 0.233]} />
        </group>
        <group position={[-399.195, 270.468, -16.124]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} scale={294.132}>
          <mesh geometry={nodes.Plane008_Black_0.geometry} material={materials.Black} />
          <mesh geometry={nodes.Plane008_Screen_0.geometry} material={materials.Screen} />
        </group>
        <group position={[-342.518, 169.571, 310.819]} rotation={[-Math.PI / 2, 0, 0]} scale={44.811}>
          <mesh geometry={nodes.Plane009_Black006_0.geometry} material={materials['Black.006']} />
          <mesh geometry={nodes.Circle010_Black002_0.geometry} material={materials['Black.002']} position={[1.049, 0, 2.713]} rotation={[0, Math.PI / 2, 0]} scale={0.602} />
          <mesh geometry={nodes.Circle014_Black002_0.geometry} material={materials['Black.002']} position={[1.049, 0, -0.282]} rotation={[0, Math.PI / 2, 0]} scale={0.602} />
        </group>
        <mesh geometry={nodes.Cube015_Black_0.geometry} material={materials.Black} position={[-281.171, 18.478, 17.953]} rotation={[Math.PI / 2, 0, 0]} scale={[-0.787, 2.059, 0.787]} />
        <mesh geometry={nodes.Cylinder_Black_0.geometry} material={materials.Black} position={[-281.42, 18.164, 14.42]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={0.73} />
        <mesh geometry={nodes.Plane029_bg_0.geometry} material={materials.material} position={[0, -31.123, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={1679.843} />
        <mesh geometry={nodes.Cube001_Black004_0.geometry} material={materials['Black.004']} position={[0, 288.949, -488.046]} rotation={[-Math.PI / 2, 0, 0]} scale={[272.431, 36.542, 152.506]} />
        <mesh geometry={nodes.Circle007_Patern_fabric_A_0.geometry} material={materials.Patern_fabric_A} position={[-21.092, 0.023, 275.147]} rotation={[-Math.PI / 2, 0, 0]} scale={[115.721, 115.721, 133.505]} />
        <mesh geometry={nodes.Plane005_Marble002_0.geometry} material={materials['Marble.002']} position={[-340.739, 82.888, -13.524]} rotation={[-Math.PI / 2, 0, 0]} scale={[65.413, 257.658, 94.079]} />
        <mesh geometry={nodes.Plane006_White_0.geometry} material={materials.White} position={[-340.739, 33.863, -13.524]} rotation={[-Math.PI / 2, 0, 0]} scale={[65.413, 258.079, 94.079]} />
        <mesh geometry={nodes.Circle008_Metall001_0.geometry} material={materials['Metall.001']} position={[-294.205, 33.863, 223.208]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.514, 10.514, 19.597]} />
        <mesh geometry={nodes.Plane007_Black003_0.geometry} material={materials['Black.003']} position={[-340.739, 33.863, -13.524]} rotation={[-Math.PI / 2, 0, 0]} scale={[65.413, 258.079, 94.079]} />
        <mesh geometry={nodes.Circle019_Black002_0.geometry} material={materials['Black.002']} position={[-295.531, 222.951, 310.818]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={18.38} />
        <mesh geometry={nodes.Cube011_Floor002_0.geometry} material={materials['Floor.002']} position={[0, 288.949, -480.326]} rotation={[-Math.PI / 2, 0, 0]} scale={[272.431, 36.542, 152.506]} />
        <mesh geometry={nodes['Cube012_��������_0'].geometry} material={materials.material_23} position={[0, 288.949, -477.4]} rotation={[-Math.PI / 2, 0, 0]} scale={[272.431, 36.542, 152.506]} />
        <mesh geometry={nodes.Cube013_Metall_0.geometry} material={materials.Metall} position={[0, 288.949, -412.312]} rotation={[-Math.PI / 2, 0, 0]} scale={[274.813, 317.906, 152.506]} />
        <mesh geometry={nodes.Cube014_Material_0.geometry} material={materials.Material} position={[0, 288.949, -459.415]} rotation={[-Math.PI / 2, 0, 0]} scale={[261.954, 36.542, 152.506]} />
        <mesh geometry={nodes.Circle023_White_0.geometry} material={materials.White} position={[305.283, 0.671, 314.389]} rotation={[-Math.PI / 2, 0, 0]} scale={67.882} />
        <mesh geometry={nodes.Circle024_Metall_0.geometry} material={materials.Metall} position={[305.283, 66.169, 314.389]} rotation={[-Math.PI / 2, 0, 0]} scale={64.652} />
        <mesh geometry={nodes.Circle025_White001_0.geometry} material={materials['White.001']} position={[305.283, 67.374, 314.389]} rotation={[-Math.PI / 2, 0, 0]} scale={59.003} />
        <mesh geometry={nodes.Plane011_Black_0.geometry} material={materials.Black} position={[-311.495, 41.505, -68.708]} rotation={[-Math.PI / 2, 0, 0]} scale={[32.535, 32.535, 11.767]} />
        <mesh geometry={nodes.Plane013_White_0.geometry} material={materials.White} position={[-311.495, 34.45, -49.905]} rotation={[-Math.PI / 2, 0, 0]} scale={[36.596, 260.781, 101.865]} />
        <mesh geometry={nodes.Circle026_Black_0.geometry} material={materials.Black} position={[-311.495, 41.505, -68.708]} rotation={[-Math.PI / 2, 0, 0]} scale={27.289} />
        <mesh geometry={nodes.Plane014_Black_0.geometry} material={materials.Black} position={[-311.495, 34.45, -49.905]} rotation={[-Math.PI / 2, 0, 0]} scale={[36.596, 260.781, 101.865]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/iso_room.glb')
